#!/bin/bash
DIR="$(pwd)"
cd ~/Github/simavr/examples/board_simduino/
export SIMAVR_UART_XTERM=1
./obj-x86_64-pc-linux-gnu/simduino.elf &
cd -
sleep 1
avrdude -p m328p -c arduino -P /tmp/simavr-uart0 -U flash:w:tmp/myforth.ino.hex
echo "Press ENTER to stop it all..."
read ANS
killall picocom
killall simduino.elf
